/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "M2_IN2_aliases.h"
#include "M2_IN2.h"
#include "ADC_SAR_Seq_1.h"
#include "input_signal_0_aliases.h"
#include "input_signal_0.h"
#include "PWM_1.h"
#include "input_signal_1_aliases.h"
#include "input_signal_1.h"
#include "input_signal_2_aliases.h"
#include "input_signal_2.h"
#include "isr_eoc_1.h"
#include "PWM_2.h"
#include "M1_IN2_aliases.h"
#include "M1_IN2.h"
#include "M2_IN1_aliases.h"
#include "M2_IN1.h"
#include "M1_IN1_aliases.h"
#include "M1_IN1.h"
#include "input_signal_3_aliases.h"
#include "input_signal_3.h"
#include "input_signal_4_aliases.h"
#include "input_signal_4.h"
#include "Clock_PWM.h"
#include "L_ENCD_aliases.h"
#include "L_ENCD.h"
#include "L_ENCD2_aliases.h"
#include "L_ENCD2.h"
#include "QuadDec_2.h"
#include "QuadDec_1.h"
#include "R_ENCD_aliases.h"
#include "R_ENCD.h"
#include "timer_clock.h"
#include "R_ENCD2_aliases.h"
#include "R_ENCD2.h"
#include "Clock_ENCD.h"
#include "Timer_1.h"
#include "isr_speed_timer.h"
#include "led_aliases.h"
#include "led.h"
#include "ADC_SAR_Seq_1_SAR.h"
#include "ADC_SAR_Seq_1_IntClock.h"
#include "ADC_SAR_Seq_1_TempBuf_dma.h"
#include "ADC_SAR_Seq_1_FinalBuf_dma.h"
#include "ADC_SAR_Seq_1_IRQ.h"
#include "QuadDec_2_Cnt16.h"
#include "QuadDec_1_Cnt16.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

